{% set name = "factory_boy" %}
{% set version = "2.9.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "340c602f6fed2d8dd160397f28f2c0219e937f0488460450e8e5bf2add020ed6" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools >=0.8.0

  run:
    - python
    - faker >=0.7.0

test:
  imports:
    - factory

about:
  home: https://github.com/FactoryBoy/factory_boy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "A versatile test fixtures replacement based on thoughtbot's factory_girl for Ruby."
  dev_url: https://github.com/FactoryBoy/factory_boy
  doc_url: https://factoryboy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
