{% set name = "factory_boy" %}
{% set version = "2.11.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "6f25cc4761ac109efd503f096e2ad99421b1159f01a29dbb917359dcd68e08ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools >=0.8.0

  run:
    - python
    - faker >=0.7.0

test:
  imports:
    - factory

about:
  home: https://github.com/FactoryBoy/factory_boy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "A versatile test fixtures replacement based on thoughtbot's factory_girl for Ruby."
  dev_url: https://github.com/FactoryBoy/factory_boy
  doc_url: https://factoryboy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
